application: pgwebhook
version: 20150923
runtime: go
api_version: go1

handlers:
- url: /bower_components
  static_dir: bower_components
- url: /components
  static_dir: templates/components
- url: /static
  static_dir: static
- url: /hooks/.*
  script: _go_app
- url: /.*
  script: _go_app
  login: required
