application: pgwebhook
version: 1
runtime: go
api_version: go1

handlers:
- url: /bower_components
  static_dir: bower_components
- url: /hooks/.*
  script: _go_app
- url: /.*
  script: _go_app
  login: required
