# application: pgwebhook
# version: 1-0-0
runtime: go111

handlers:
- url: /bower_components
  static_dir: bower_components
  expiration: 1d
- url: /components
  static_dir: templates/components
- url: /static
  static_dir: static
- url: /
  script: auto
- url: /w.*
  script: auto
- url: /telegram/.*
  script: auto
- url: /.*
  script: auto
  login: required
